---
repos:
  - repo: https://github.com/psf/black
    rev: 21.5b1
    hooks:
      - id: black
        exclude: tests/test_pattern_matching.py
        language_version: python3.8

  - repo: https://github.com/PyCQA/isort
    rev: 5.8.0
    hooks:
      - id: isort
        additional_dependencies: [toml]
        files: \.py$
        language_version: python3.10

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        language_version: python3.10

  - repo: https://github.com/econchick/interrogate
    rev: 1.4.0
    hooks:
      - id: interrogate
        exclude: tests/test_pattern_matching.py
        args: [tests]
        language_version: python3.10

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
        language_version: python3.10
      - id: check-toml
