---
version: 2
formats: all

python:
  # Keep version in sync with tox.ini (docs and gh-actions).
  version: "3.10"

  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
